import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { useLoading } from "./_app";

const Page2 = () => {
  return (
    <>
      <Head>
        <title>第 2 頁</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>第 2 頁</h1>
        <Link href="/">回首頁</Link>
      </main>
    </>
  );
};

export default Page2;
