import { useState, useEffect, useContext, useRef } from "react";
import Head from "next/head";
import Link from "next/link";
import LoadingContext from "@/context/LoadingContext";
import { useRouter } from "next/navigation";

const Page1 = () => {
  const hasRun = useRef(false);
  const { loading, setLoading, setWaittingTime } = useContext(LoadingContext);
  const [data, setData] = useState(null);
  const router = useRouter();
  
  const waitting = (t) => {
    return new Promise(resolve => {
      setTimeout(()=>{
        resolve();
      },t);
    });
  }

  useEffect(() => {
    if (hasRun.current) return;
    hasRun.current = true;
    setWaittingTime(0)
    const fetchData = async () => {
      const num = Math.floor(Math.random()*10)+5
      setLoading(true);
      const response = await fetch(`https://randomuser.me/api/?results=${num}`);
      const result = await response.json();
      await waitting(5000)
      setData(result);
      console.log(result);
      
      setLoading(false);
    };
    fetchData();
  }, []);

  const getData = async ()=>{
    setLoading(true);
    const response = await fetch("/api/page1");
    const result = await response.json();
    setData(result);
    setLoading(false);
  }

  if (loading) {
    return null;
  }

  return (
    <>
      <Head>
        <title>第一頁</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>第一頁</h1>
        <div className="btn btn-primary mb-1" onClick={getData}>載入內容</div><br />
        <Link className="btn btn-primary" href="/">回首頁</Link>
      </main>
    </>
  );
};

export default Page1;
