import Head from "next/head";
import Link from "next/link";

const Page1 = () => {
    return (
        <>
          <Head>
            <title>第一頁</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="container">
            <h1>第一頁</h1>
            <Link href="/">回首頁</Link>
          </main>
        </>
      );
}

export default Page1;